### ISSUE TITLE
How can I get the live stream videos of your tutorial?

### ISSUE THREAD

**Issue by pleaseRedo** [asyml/aaai_tutorial#1]
I missed your tutorial, yet only find your slides. I googled the video but failed.  Is it possible to get your stream videos? Thanks

**Comment by hunterhector** [comment]
It looks like AAAI didn't record the video. I will contact AAAI again to double-check. 

Further, we will be giving a similar tutorial (though adapted) at GTC, which might be available online later or streamable:

https://www.nvidia.com/en-us/gtc/session-catalog/?search=modulairzing%20natural%20language%20processing

If the tutorial won't have video records again, we will try to personally record the tutorial this time.

**Comment by hunterhector** [comment]
We are unsure of the GTC schedule yet.

**Comment by pleaseRedo** [comment]
> We are unsure of the GTC schedule yet.

Thanks for the the reply. Will wait for GTC event

**Comment by hunterhector** [comment]
The GTC session is here:
https://developer.nvidia.com/gtc/2020/video/s21560-vid

Probably need to register to see it (likely to be free)

**Comment by pleaseRedo** [comment]
> The GTC session is here:
> https://developer.nvidia.com/gtc/2020/video/s21560-vid
> 
> Probably need to register to see it (likely to be free)

cheers! Thanks for sharing it
